"""BE-SEC-02: 统一错误码。

所有向客户端返回的业务错误均应使用本模块定义的常量，避免直接暴露
原始异常字符串、内部状态或堆栈信息。原始异常需在服务端通过
`logger.error(..., exc_info=True)` 记录，并通过 `request_id` 关联。

错误码分组约定
----------------
本模块按业务域将错误码划分为以下命名空间分组（仅作注释分隔，未引入
语言层面的子命名空间，以保持对现有 ``ErrorCode.XXX`` 调用模式的完全
向后兼容）：

1.  通用             - 跨域通用的顶层错误（INTERNAL_ERROR / INVALID_REQUEST 等）
2.  认证             - 登录、注册、Token、邀请码、账户锁定
3.  Agent            - 数字员工生命周期、构建、版本、看门狗
4.  文件/处理        - 文件上传、病毒扫描、向量写入、处理任务
5.  企业/成员        - 企业、成员、邀请
6.  技能             - 技能 CRUD、审核、技能包 URL 拉取
7.  模板             - B6 数字员工模板
8.  对话/循环/规划   - 对话、消息、Loop 闭环优化、隐式反馈
9.  业务指标         - 指标查询、任务规划
10. 设置向导         - 首次设置向导会话
11. 目录             - 文件夹目录树

字符串值不可变约束
------------------
错误码的字符串值（如 ``"INTERNAL_ERROR"``）可能已被序列化到数据库、
日志、审计链与前端展示，**严禁修改任何常量的字符串值**。新增错误码
应归入对应分组并遵循 ``UPPER_SNAKE_CASE`` 命名。如需移除错误码，请
先确认无任何引用（参见本文件末尾 ``ERROR_CODE_GROUPS`` 用于死代码扫描）。

向后兼容约束
------------
现有大量代码以 ``ErrorCode.XXX`` 形式访问错误码，并以
``ErrorCode.XXX == "INTERNAL_ERROR"`` 进行字符串比较。因此 ``ErrorCode``
保持普通 ``class`` 形式（常量即 ``str`` 字面量），不改为 ``Enum``；
``__all__`` 与 ``ERROR_CODE_GROUPS`` 仅为补充元数据，不影响访问路径。
"""


class ErrorCode:
    # ===== 通用 =====
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    FORBIDDEN = "FORBIDDEN"
    UNAUTHORIZED = "UNAUTHORIZED"
    OPERATION_FAILED = "OPERATION_FAILED"

    # ===== 认证 =====
    REGISTRATION_FAILED = "REGISTRATION_FAILED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    MISSING_REFRESH_TOKEN = "MISSING_REFRESH_TOKEN"
    INVITE_REGISTRATION_FAILED = "INVITE_REGISTRATION_FAILED"
    INVITE_NOT_FOUND = "INVITE_NOT_FOUND"
    INVITE_USED_OR_CANCELLED = "INVITE_USED_OR_CANCELLED"
    # M9: 账户因连续登录失败被临时锁定
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    # BE-SEC-08: 公开注册已关闭
    REGISTRATION_DISABLED = "REGISTRATION_DISABLED"

    # ===== Agent =====
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    AGENT_ACCESS_DENIED = "AGENT_ACCESS_DENIED"
    AGENT_STATUS_INVALID = "AGENT_STATUS_INVALID"
    AGENT_FOLDER_MISSING = "AGENT_FOLDER_MISSING"
    AGENT_WATCHDOG_UNAVAILABLE = "AGENT_WATCHDOG_UNAVAILABLE"
    AGENT_WATCH_FAILED = "AGENT_WATCH_FAILED"
    AGENT_INCREMENTAL_FAILED = "AGENT_INCREMENTAL_FAILED"
    AGENT_BUILD_INVALID = "AGENT_BUILD_INVALID"
    AGENT_RESUME_BUILD_INVALID = "AGENT_RESUME_BUILD_INVALID"
    AGENT_THREAD_NOT_FOUND = "AGENT_THREAD_NOT_FOUND"
    BUILD_STATE_INVALID = "BUILD_STATE_INVALID"
    AGENT_VERSION_NOT_FOUND = "AGENT_VERSION_NOT_FOUND"
    AGENT_VERSION_ROLLBACK_FAILED = "AGENT_VERSION_ROLLBACK_FAILED"

    # ===== 文件/处理 =====
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_ACCESS_DENIED = "FILE_ACCESS_DENIED"
    FILE_PATH_INVALID = "FILE_PATH_INVALID"
    FILE_NOT_ON_DISK = "FILE_NOT_ON_DISK"
    FILE_BINARY_CONTENT = "FILE_BINARY_CONTENT"
    FILE_READ_FAILED = "FILE_READ_FAILED"
    FILE_PROCESSING_FAILED = "FILE_PROCESSING_FAILED"
    FILE_VECTOR_WRITE_FAILED = "FILE_VECTOR_WRITE_FAILED"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_EMPTY = "FILE_EMPTY"
    FILE_PREVIEW_TYPE_NOT_SUPPORTED = "FILE_PREVIEW_TYPE_NOT_SUPPORTED"
    FILE_CONFIDENTIAL_ACCESS_DENIED = "FILE_CONFIDENTIAL_ACCESS_DENIED"
    # P0-DoS: 批量上传文件数超限（默认上限 50）
    BATCH_UPLOAD_TOO_MANY_FILES = "BATCH_UPLOAD_TOO_MANY_FILES"
    # T21: ClamAV 病毒扫描检测到恶意文件
    FILE_VIRUS_DETECTED = "FILE_VIRUS_DETECTED"
    # T21: 病毒扫描服务不可用（ClamAV 连接失败）
    FILE_SCAN_UNAVAILABLE = "FILE_SCAN_UNAVAILABLE"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_ACCESS_DENIED = "TASK_ACCESS_DENIED"
    TASK_ALREADY_FINISHED = "TASK_ALREADY_FINISHED"

    # ===== 企业/成员 =====
    ENTERPRISE_NOT_FOUND = "ENTERPRISE_NOT_FOUND"
    ENTERPRISE_DELETED = "ENTERPRISE_DELETED"
    ENTERPRISE_ACCESS_DENIED = "ENTERPRISE_ACCESS_DENIED"
    ENTERPRISE_INVITE_FAILED = "ENTERPRISE_INVITE_FAILED"
    MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND"
    MEMBER_OPERATION_INVALID = "MEMBER_OPERATION_INVALID"
    CANNOT_REMOVE_SELF = "CANNOT_REMOVE_SELF"
    CANNOT_CHANGE_SELF_ROLE = "CANNOT_CHANGE_SELF_ROLE"
    INVITATION_NOT_FOUND = "INVITATION_NOT_FOUND"
    INVITATION_STATUS_INVALID = "INVITATION_STATUS_INVALID"
    INVITE_MAX_USES_INVALID = "INVITE_MAX_USES_INVALID"
    INVITE_EMAIL_MISMATCH = "INVITE_EMAIL_MISMATCH"
    INVITE_EXPIRED = "INVITE_EXPIRED"
    INVITE_USED_UP = "INVITE_USED_UP"
    INVITE_ENTERPRISE_NOT_FOUND = "INVITE_ENTERPRISE_NOT_FOUND"

    # ===== 技能 =====
    SKILL_NOT_FOUND = "SKILL_NOT_FOUND"
    SKILL_ACCESS_DENIED = "SKILL_ACCESS_DENIED"
    SKILL_EXECUTION_FORBIDDEN = "SKILL_EXECUTION_FORBIDDEN"
    SKILL_NOT_FOUND_OR_INVALID = "SKILL_NOT_FOUND_OR_INVALID"
    SKILL_FILE_TYPE_NOT_ALLOWED = "SKILL_FILE_TYPE_NOT_ALLOWED"
    SKILL_FILE_SIZE_EXCEEDED = "SKILL_FILE_SIZE_EXCEEDED"
    SKILL_GENERATION_FAILED = "SKILL_GENERATION_FAILED"
    SKILL_IMPORT_INVALID = "SKILL_IMPORT_INVALID"
    SKILL_SCREENING_FAILED = "SKILL_SCREENING_FAILED"
    SKILL_REVIEW_INVALID_STATE = "SKILL_REVIEW_INVALID_STATE"
    SKILL_REVIEW_ALREADY_COMPLETE = "SKILL_REVIEW_ALREADY_COMPLETE"
    SKILL_PENDING_APPROVAL = "SKILL_PENDING_APPROVAL"
    # M11: 技能包 URL 拉取相关错误
    SKILL_PACKAGE_URL_INVALID = "SKILL_PACKAGE_URL_INVALID"
    SKILL_PACKAGE_URL_UNREACHABLE = "SKILL_PACKAGE_URL_UNREACHABLE"
    SKILL_PACKAGE_URL_TOO_LARGE = "SKILL_PACKAGE_URL_TOO_LARGE"
    SKILL_PACKAGE_EXTRACT_FAILED = "SKILL_PACKAGE_EXTRACT_FAILED"

    # ===== 模板（B6 数字员工模板） =====
    TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND"
    TEMPLATE_ACCESS_DENIED = "TEMPLATE_ACCESS_DENIED"
    TEMPLATE_APPLY_FAILED = "TEMPLATE_APPLY_FAILED"

    # ===== 本地路径授权（协作工作台与本地工具桥接） =====
    LOCAL_PATH_NOT_FOUND = "LOCAL_PATH_NOT_FOUND"
    LOCAL_PATH_ACCESS_DENIED = "LOCAL_PATH_ACCESS_DENIED"
    LOCAL_PATH_LIMIT_EXCEEDED = "LOCAL_PATH_LIMIT_EXCEEDED"
    LOCAL_PATH_RUNNER_OFFLINE = "LOCAL_PATH_RUNNER_OFFLINE"
    LOCAL_PATH_TOKEN_INVALID = "LOCAL_PATH_TOKEN_INVALID"
    LOCAL_PATH_TOKEN_EXPIRED = "LOCAL_PATH_TOKEN_EXPIRED"
    LOCAL_PATH_CLAIMED = "LOCAL_PATH_CLAIMED"
    LOCAL_PATH_SCOPE_FORBIDDEN = "LOCAL_PATH_SCOPE_FORBIDDEN"
    LOCAL_PATH_TASK_FAILED = "LOCAL_PATH_TASK_FAILED"

    # ===== 对话/循环/规划 =====
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
    CONVERSATION_ACCESS_DENIED = "CONVERSATION_ACCESS_DENIED"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    MESSAGE_ACCESS_DENIED = "MESSAGE_ACCESS_DENIED"
    LOOP_AGENT_NOT_FOUND = "LOOP_AGENT_NOT_FOUND"
    FEEDBACK_ANALYSIS_INVALID = "FEEDBACK_ANALYSIS_INVALID"
    KNOWLEDGE_GAP_INVALID = "KNOWLEDGE_GAP_INVALID"
    OPTIMIZE_RETRIEVAL_INVALID = "OPTIMIZE_RETRIEVAL_INVALID"
    LOOP_STATUS_INVALID = "LOOP_STATUS_INVALID"
    LOOP_STATS_INVALID = "LOOP_STATS_INVALID"
    # O-08: Loop 闭环优化应用
    OPTIMIZATION_NOT_FOUND = "OPTIMIZATION_NOT_FOUND"
    OPTIMIZATION_ALREADY_APPLIED = "OPTIMIZATION_ALREADY_APPLIED"
    OPTIMIZATION_APPLY_FAILED = "OPTIMIZATION_APPLY_FAILED"
    # M12: 隐式反馈收集
    IMPLICIT_FEEDBACK_INVALID = "IMPLICIT_FEEDBACK_INVALID"

    # ===== 业务指标 =====
    METRICS_INVALID = "METRICS_INVALID"
    PLAN_NOT_FOUND = "PLAN_NOT_FOUND"
    PLAN_ACCESS_DENIED = "PLAN_ACCESS_DENIED"
    STEP_NOT_FOUND = "STEP_NOT_FOUND"

    # ===== 设置向导 =====
    SETUP_ENTERPRISE_REQUIRED = "SETUP_ENTERPRISE_REQUIRED"
    SETUP_SESSION_NOT_FOUND = "SETUP_SESSION_NOT_FOUND"
    SETUP_ACCESS_DENIED = "SETUP_ACCESS_DENIED"
    SETUP_MESSAGE_INVALID = "SETUP_MESSAGE_INVALID"
    SETUP_PLAN_NOT_FOUND = "SETUP_PLAN_NOT_FOUND"
    SETUP_CONFIRM_FAILED = "SETUP_CONFIRM_FAILED"

    # ===== 目录 =====
    FOLDER_NOT_FOUND = "FOLDER_NOT_FOUND"
    FOLDER_ACCESS_DENIED = "FOLDER_ACCESS_DENIED"
    FOLDER_PATH_INVALID = "FOLDER_PATH_INVALID"


# ----- 显式导出 -----
# `__all__` 只能列模块级真实存在的名字。错误码常量是 `ErrorCode` 的**类属性**
# （`ErrorCode.NOT_FOUND`），不是模块级名字；此前把 119 个常量名写进 `__all__`
# 会让 `from app.utils.error_codes import *` 直接抛 AttributeError（F822）。
# 需要"全部错误码清单"请用下面的 `ERROR_CODE_GROUPS`。
__all__ = ["ErrorCode", "ERROR_CODE_GROUPS"]


# ----- 分组索引：按业务域列出所有错误码字符串值，便于工具化检查（死代码扫描、归属校验） -----
# 键为分组标识（snake_case），值为该分组下所有错误码的字符串值列表。
# 新增错误码时务必同步追加到对应分组，否则会被死代码扫描误报。
ERROR_CODE_GROUPS: dict[str, list[str]] = {
    "general": [
        ErrorCode.INTERNAL_ERROR,
        ErrorCode.INVALID_REQUEST,
        ErrorCode.NOT_FOUND,
        ErrorCode.FORBIDDEN,
        ErrorCode.UNAUTHORIZED,
        ErrorCode.OPERATION_FAILED,
    ],
    "auth": [
        ErrorCode.REGISTRATION_FAILED,
        ErrorCode.INVALID_CREDENTIALS,
        ErrorCode.INVALID_REFRESH_TOKEN,
        ErrorCode.MISSING_REFRESH_TOKEN,
        ErrorCode.INVITE_REGISTRATION_FAILED,
        ErrorCode.INVITE_NOT_FOUND,
        ErrorCode.INVITE_USED_OR_CANCELLED,
        ErrorCode.ACCOUNT_LOCKED,
        ErrorCode.REGISTRATION_DISABLED,
    ],
    "agent": [
        ErrorCode.AGENT_NOT_FOUND,
        ErrorCode.AGENT_ACCESS_DENIED,
        ErrorCode.AGENT_STATUS_INVALID,
        ErrorCode.AGENT_FOLDER_MISSING,
        ErrorCode.AGENT_WATCHDOG_UNAVAILABLE,
        ErrorCode.AGENT_WATCH_FAILED,
        ErrorCode.AGENT_INCREMENTAL_FAILED,
        ErrorCode.AGENT_BUILD_INVALID,
        ErrorCode.AGENT_RESUME_BUILD_INVALID,
        ErrorCode.AGENT_THREAD_NOT_FOUND,
        ErrorCode.BUILD_STATE_INVALID,
        ErrorCode.AGENT_VERSION_NOT_FOUND,
        ErrorCode.AGENT_VERSION_ROLLBACK_FAILED,
    ],
    "file_processing": [
        ErrorCode.FILE_NOT_FOUND,
        ErrorCode.FILE_ACCESS_DENIED,
        ErrorCode.FILE_PATH_INVALID,
        ErrorCode.FILE_NOT_ON_DISK,
        ErrorCode.FILE_BINARY_CONTENT,
        ErrorCode.FILE_READ_FAILED,
        ErrorCode.FILE_PROCESSING_FAILED,
        ErrorCode.FILE_VECTOR_WRITE_FAILED,
        ErrorCode.FILE_UPLOAD_FAILED,
        ErrorCode.FILE_TYPE_NOT_ALLOWED,
        ErrorCode.FILE_SIZE_EXCEEDED,
        ErrorCode.FILE_EMPTY,
        ErrorCode.FILE_PREVIEW_TYPE_NOT_SUPPORTED,
        ErrorCode.FILE_CONFIDENTIAL_ACCESS_DENIED,
        ErrorCode.FILE_VIRUS_DETECTED,
        ErrorCode.FILE_SCAN_UNAVAILABLE,
        ErrorCode.BATCH_UPLOAD_TOO_MANY_FILES,
        ErrorCode.PROCESSING_FAILED,
        ErrorCode.TASK_NOT_FOUND,
        ErrorCode.TASK_ACCESS_DENIED,
        ErrorCode.TASK_ALREADY_FINISHED,
    ],
    "enterprise_member": [
        ErrorCode.ENTERPRISE_NOT_FOUND,
        ErrorCode.ENTERPRISE_DELETED,
        ErrorCode.ENTERPRISE_ACCESS_DENIED,
        ErrorCode.ENTERPRISE_INVITE_FAILED,
        ErrorCode.MEMBER_NOT_FOUND,
        ErrorCode.MEMBER_OPERATION_INVALID,
        ErrorCode.CANNOT_REMOVE_SELF,
        ErrorCode.CANNOT_CHANGE_SELF_ROLE,
        ErrorCode.INVITATION_NOT_FOUND,
        ErrorCode.INVITATION_STATUS_INVALID,
        ErrorCode.INVITE_MAX_USES_INVALID,
        ErrorCode.INVITE_EMAIL_MISMATCH,
        ErrorCode.INVITE_EXPIRED,
        ErrorCode.INVITE_USED_UP,
        ErrorCode.INVITE_ENTERPRISE_NOT_FOUND,
    ],
    "skill": [
        ErrorCode.SKILL_NOT_FOUND,
        ErrorCode.SKILL_ACCESS_DENIED,
        ErrorCode.SKILL_EXECUTION_FORBIDDEN,
        ErrorCode.SKILL_NOT_FOUND_OR_INVALID,
        ErrorCode.SKILL_FILE_TYPE_NOT_ALLOWED,
        ErrorCode.SKILL_FILE_SIZE_EXCEEDED,
        ErrorCode.SKILL_GENERATION_FAILED,
        ErrorCode.SKILL_IMPORT_INVALID,
        ErrorCode.SKILL_SCREENING_FAILED,
        ErrorCode.SKILL_REVIEW_INVALID_STATE,
        ErrorCode.SKILL_REVIEW_ALREADY_COMPLETE,
        ErrorCode.SKILL_PENDING_APPROVAL,
        ErrorCode.SKILL_PACKAGE_URL_INVALID,
        ErrorCode.SKILL_PACKAGE_URL_UNREACHABLE,
        ErrorCode.SKILL_PACKAGE_URL_TOO_LARGE,
        ErrorCode.SKILL_PACKAGE_EXTRACT_FAILED,
    ],
    "template": [
        ErrorCode.TEMPLATE_NOT_FOUND,
        ErrorCode.TEMPLATE_ACCESS_DENIED,
        ErrorCode.TEMPLATE_APPLY_FAILED,
    ],
    "local_path": [
        ErrorCode.LOCAL_PATH_NOT_FOUND,
        ErrorCode.LOCAL_PATH_ACCESS_DENIED,
        ErrorCode.LOCAL_PATH_LIMIT_EXCEEDED,
        ErrorCode.LOCAL_PATH_RUNNER_OFFLINE,
        ErrorCode.LOCAL_PATH_TOKEN_INVALID,
        ErrorCode.LOCAL_PATH_TOKEN_EXPIRED,
        ErrorCode.LOCAL_PATH_CLAIMED,
        ErrorCode.LOCAL_PATH_SCOPE_FORBIDDEN,
        ErrorCode.LOCAL_PATH_TASK_FAILED,
    ],
    "conversation_loop_planning": [
        ErrorCode.CONVERSATION_NOT_FOUND,
        ErrorCode.CONVERSATION_ACCESS_DENIED,
        ErrorCode.MESSAGE_NOT_FOUND,
        ErrorCode.MESSAGE_ACCESS_DENIED,
        ErrorCode.LOOP_AGENT_NOT_FOUND,
        ErrorCode.FEEDBACK_ANALYSIS_INVALID,
        ErrorCode.KNOWLEDGE_GAP_INVALID,
        ErrorCode.OPTIMIZE_RETRIEVAL_INVALID,
        ErrorCode.LOOP_STATUS_INVALID,
        ErrorCode.LOOP_STATS_INVALID,
        ErrorCode.OPTIMIZATION_NOT_FOUND,
        ErrorCode.OPTIMIZATION_ALREADY_APPLIED,
        ErrorCode.OPTIMIZATION_APPLY_FAILED,
        ErrorCode.IMPLICIT_FEEDBACK_INVALID,
    ],
    "metrics_planning": [
        ErrorCode.METRICS_INVALID,
        ErrorCode.PLAN_NOT_FOUND,
        ErrorCode.PLAN_ACCESS_DENIED,
        ErrorCode.STEP_NOT_FOUND,
    ],
    "setup": [
        ErrorCode.SETUP_ENTERPRISE_REQUIRED,
        ErrorCode.SETUP_SESSION_NOT_FOUND,
        ErrorCode.SETUP_ACCESS_DENIED,
        ErrorCode.SETUP_MESSAGE_INVALID,
        ErrorCode.SETUP_PLAN_NOT_FOUND,
        ErrorCode.SETUP_CONFIRM_FAILED,
    ],
    "folder": [
        ErrorCode.FOLDER_NOT_FOUND,
        ErrorCode.FOLDER_ACCESS_DENIED,
        ErrorCode.FOLDER_PATH_INVALID,
    ],
}
