"""initial schema with persistent state models

Revision ID: 76fa475662e8
Revises: 
Create Date: 2026-07-12 12:05:54.317528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fa475662e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('invite_token', sa.String(), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('knowledge_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_enterprise_id'), ['enterprise_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('enterprise_id', sa.String(length=36), nullable=True),
    sa.Column('refresh_token_hash', sa.String(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('agent_versions',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_versions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_versions_is_active'), ['is_active'], unique=False)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('vector_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_content_hash'), ['content_hash'], unique=False)

    op.create_table('optimization_histories',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optimization_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_histories_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_histories_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_histories_user_id'), ['user_id'], unique=False)

    op.create_table('processing_tasks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('agent_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('failed_files', sa.Integer(), nullable=False),
    sa.Column('knowledge_count', sa.Integer(), nullable=False),
    sa.Column('processing_time_seconds', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_tasks_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_tasks_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('setup_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setup_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setup_sessions_enterprise_id'), ['enterprise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_setup_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_setup_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_type', sa.String(length=50), nullable=False),
    sa.Column('input_type', sa.String(length=50), nullable=True),
    sa.Column('output_type', sa.String(length=50), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_agent_id'), ['agent_id'], unique=False)

    op.create_table('task_plans',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_plans_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_plans_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('satisfaction', sa.String(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    op.create_table('skill_executions',
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_executions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_executions_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_executions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_executions_user_id'))
        batch_op.drop_index(batch_op.f('ix_skill_executions_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_executions_agent_id'))

    op.drop_table('skill_executions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('task_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_plans_status'))
        batch_op.drop_index(batch_op.f('ix_task_plans_agent_id'))

    op.drop_table('task_plans')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_agent_id'))

    op.drop_table('skills')
    with op.batch_alter_table('setup_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setup_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_setup_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_setup_sessions_enterprise_id'))

    op.drop_table('setup_sessions')
    with op.batch_alter_table('processing_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_processing_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_processing_tasks_enterprise_id'))
        batch_op.drop_index(batch_op.f('ix_processing_tasks_agent_id'))

    op.drop_table('processing_tasks')
    with op.batch_alter_table('optimization_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optimization_histories_user_id'))
        batch_op.drop_index(batch_op.f('ix_optimization_histories_type'))
        batch_op.drop_index(batch_op.f('ix_optimization_histories_agent_id'))

    op.drop_table('optimization_histories')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_content_hash'))
        batch_op.drop_index(batch_op.f('ix_files_agent_id'))

    op.drop_table('files')
    op.drop_table('conversations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_versions_is_active'))
        batch_op.drop_index(batch_op.f('ix_agent_versions_agent_id'))

    op.drop_table('agent_versions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_enterprise_id'))

    op.drop_table('agents')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
