"""add progress and message to processing_tasks

Revision ID: 22af9efcfa3d
Revises: 76fa475662e8
Create Date: 2026-07-12 12:13:03.430510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22af9efcfa3d'
down_revision: Union[str, None] = '76fa475662e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_tasks', schema=None) as batch_op:
        batch_op.drop_column('message')
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
